# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master, develop, nix-shell-cache-ci-2020-01-20 ]
  pull_request:
    branches: [ master, develop, nix-shell-cache-ci-2020-01-20 ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Install Nix
      uses: cachix/install-nix-action@v12
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        set -xe
        mkdir -p ~/.config/nix/
        cp ./nix.conf ~/.config/nix/
    - run: nix-shell --command "lair-keystore --version"
